services:
  - type: web
    name: honeymoon-monitor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run honeymoon_monitor.py --server.port $PORT"
    autoDeploy: true