[credentials]
  [credentials.user1]
  name = "Alice Example"
  password = "secret-password"
  # add more users as needed

[cookie]
  name = "auth_cookie"
  key = "YOUR_RANDOM_SECURE_KEY"
  expiry_days = 30
