[credentials]
  [credentials.user1]
  name = "Alice Example"
  password = "mypassword1"
  [credentials.user2]
  name = "Bob Example"
  password = "mypassword2"

[cookie]
  name = "honeymoon_auth"
  key = "a-very-secret-random-string"  # at least 16 chars
  expiry_days = 7
